NAME = cub3D
GNL = gnl.a

GNL_DIR = ./gnl
IMG_DIR = ./img
MLX_DIR = ./mlx
INC_DIR = ./includes

CC = gcc
GCC_FLAG = -Wall -Wextra -Werror
RM = rm
RMFLAGS = -f
AR = ar crs

MLX_FLAG = -framework OpenGL -framework Appkit

OBJS = ./*.o
GNL_SRC_FILES = gnl/get_next_line_bonus \
			gnl/get_next_line_bonus \

# GREEN = \033[32m
# PURPLE = \033[35m
# MINT = \033[36m
# RED = \033[31m
# BLINK = \033[5m
# BOLD = \033[1m
# BACKGRAY = \033[100m
# NO_COLOR = \e[0m

# all : $(NAME)

# $(NAME) : $(OBJS) 
# 	@echo "${PURPLE}[${RED} Makefile${PURPLE} :starting.. ]"
# 	@(make -C $(LIBFT_DIR))
# 	@echo "${PURPLE}->making libft.a , and add src.o.."
# 	@echo "${PURPLE}->resting.. drinking some coffee..."
# 	@(cp $(LIBFT_DIR)/$(LIBFT) .)
# 	@(mv $(LIBFT) $(NAME))
# 	@($(AR) $(NAME) $(OBJS))
# 	@make clean
# 	@echo "${MINT}making Done."

# $(OBJS) : 
# 	@$(CC) $(CFLAGS) -g -I $(LIBFT_INC_DIR) -I $(INC_DIR) -c $(SRCS)

# all : $(NAME)

# run :
# 	$(CC) 2d_map.c -L $(MLX_DIR) -l mlx $(MLX_FLAG) 
# 	./a.out
# 	rm -rf ./a.out
